CREATE TABLE PublishedRides
(
	[PRID] BIGINT IDENTITY PRIMARY KEY,
	[UserName] NVARCHAR(100) NOT NULL,
	[RideTime] DATETIME NOT NULL,
	[From] BIGINT NOT NULL FOREIGN KEY REFERENCES Address(AID),
	[To] BIGINT NOT NULL FOREIGN KEY REFERENCES Address(AID),
	[Seats] INT NOT NULL,
	[Vehicle] NVARCHAR(100) NULL,
	[VehicleNumber] NVARCHAR(50) NOT NULL
)



CREATE TABLE Address
(
	[AID] BIGINT IDENTITY PRIMARY KEY,
	[HFB] NVARCHAR(100) NOT NULL,
	[Locality] NVARCHAR(100) NOT NULL,
	[Landmark] NVARCHAR(100) NULL,
	[City] NVARCHAR(50) NOT NULL,
	[State] NVARCHAR(100) NOT NULL,
	[Pin] NVARCHAR(20) NOT NULL,
	[Lat] FLOAT NOT NULL,
	[Long] FLOAT NOT NULL
)